version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    links:
      - db

  controller:
    image: ogar-controller
    #restart: always
    restart: "no"
    links:
     - db

  web:
    image: ogar-web
    #restart: always
    restart: "no"
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        failure_action: rollback

  haproxy:
    image: ogar-haproxy
    #restart: always
    restart: "no"
    ports:
      - "80:80"
      - "443:443"
    links:
      - controller
      - web
      - adminer
    extra_hosts:
      - "logger:192.168.1.200"

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8001:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      update_config:
        failure_action: rollback
      placement:
        constraints:
          - 'node.role == manager'