version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    links:
      - db

  controller:
    image: ogar-controller
    #restart: always
    restart: no
    links:
     - db

  web:
    image: ogar-web
    #restart: always
    restart: no

  haproxy:
    image: ogar-haproxy
    #restart: always
    restart: no
    ports:
      - "80:80"
      - "443:443"
    links:
      - controller
      - web
      - adminer
    extra_hosts:
      - "logger:192.168.1.200"